version: "3"
services:
  server:
    build:
      context: ./docker/server
      dockerfile: Dockerfile-dev
    volumes:
      - ./server:/go/src/app
    ports:
      - "8080:8080"
  client:
    build:
      context: ./docker/client
      dockerfile: Dockerfile-dev
    volumes:
      - ./client:/var/app
    ports:
      - "8081:8081"
