apiVersion: v1
kind: Service
metadata:
  name: go-chat
  labels:
    name: go-chat
spec:
  selector:
    name: go-chat
  type: LoadBalancer
  loadBalancerIP: 35.221.119.83
  ports:
    - port: 8081
      name: client
      targetPort: 8081
    - port: 8080
      name: server
      targetPort: 8080
